export default function InsightsStats() {
  const stats = [
    {
      icon: 'ri-user-star-line',
      number: '500+',
      label: 'Featured Founders',
      description: 'Industry leaders sharing their journey'
    },
    {
      icon: 'ri-trophy-line',
      number: '1M+',
      label: 'App Downloads',
      description: 'Generated by featured companies'
    },
    {
      icon: 'ri-chat-quote-line',
      number: '300+',
      label: 'Client Reviews',
      description: 'Real testimonials from satisfied clients'
    },
    {
      icon: 'ri-rocket-line',
      number: '150+',
      label: 'Success Stories',
      description: 'Documented growth achievements'
    }
  ];

  return (
    <section className="py-16 bg-gradient-to-br from-[#f7f5ef] to-white">
      <div className="max-w-7xl mx-auto px-6 sm:px-8 lg:px-12">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-[#1F2853] mb-4" style={{ fontFamily: 'Manrope, sans-serif' }}>
            Impact by the Numbers
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto" style={{ fontFamily: 'Poppins, sans-serif' }}>
            Our insights platform connects you with the most successful founders and their proven strategies
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {stats.map((stat, index) => (
            <div key={index} className="bg-white rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 p-8 text-center group border border-gray-100">
              <div className="w-16 h-16 bg-gradient-to-br from-[#f25a1a] to-[#ff7043] rounded-full flex items-center justify-center mx-auto mb-6 group-hover:scale-110 transition-transform duration-300">
                <div className="w-8 h-8 flex items-center justify-center text-white">
                  <i className={`${stat.icon} text-2xl`}></i>
                </div>
              </div>
              
              <div className="text-4xl font-bold text-[#1F2853] mb-2" style={{ fontFamily: 'Manrope, sans-serif' }}>
                {stat.number}
              </div>
              
              <h3 className="text-xl font-semibold text-[#1F2853] mb-3" style={{ fontFamily: 'Manrope, sans-serif' }}>
                {stat.label}
              </h3>
              
              <p className="text-gray-600 text-sm leading-relaxed" style={{ fontFamily: 'Poppins, sans-serif' }}>
                {stat.description}
              </p>
            </div>
          ))}
        </div>

        {/* Call to Action */}
        <div className="text-center mt-12">
          <div className="bg-gradient-to-r from-[#1F2853] to-[#2a3a6b] rounded-xl p-8 text-white">
            <h3 className="text-2xl font-bold mb-4" style={{ fontFamily: 'Manrope, sans-serif' }}>
              Want to Share Your Story?
            </h3>
            <p className="text-lg mb-6 opacity-90 max-w-2xl mx-auto" style={{ fontFamily: 'Poppins, sans-serif' }}>
              Join our community of successful founders and inspire the next generation of entrepreneurs
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button className="bg-[#f25a1a] hover:bg-[#d14815] text-white px-8 py-3 rounded-lg font-semibold transition-all duration-300 hover:scale-105 whitespace-nowrap" style={{ fontFamily: 'Poppins, sans-serif' }}>
                Submit Your Story
              </button>
              <button className="bg-white/10 hover:bg-white/20 text-white border border-white/30 px-8 py-3 rounded-lg font-semibold transition-all duration-300 hover:scale-105 whitespace-nowrap" style={{ fontFamily: 'Poppins, sans-serif' }}>
                Become a Reviewer
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}