import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { siteContentApi } from '../../../lib/api';

const FALLBACK_STATS = [
  { icon: 'ri-user-star-line', value: '500+', label: 'Featured Founders' },
  { icon: 'ri-trophy-line',    value: '1M+',  label: 'App Downloads' },
  { icon: 'ri-chat-quote-line',value: '300+', label: 'Client Reviews' },
  { icon: 'ri-rocket-line',    value: '150+', label: 'Success Stories' },
];

const FALLBACK_DESCRIPTIONS: Record<string, string> = {
  'Featured Founders': 'Industry leaders sharing their journey',
  'App Downloads': 'Generated by featured companies',
  'Client Reviews': 'Real testimonials from satisfied clients',
  'Success Stories': 'Documented growth achievements',
};

export default function InsightsStats() {
  const { data: statsSection } = useQuery({
    queryKey: ['page-section', 'insights', 'stats'],
    queryFn: () => siteContentApi.section('insights', 'stats'),
  });

  const { data: ctaSection } = useQuery({
    queryKey: ['page-section', 'insights', 'cta'],
    queryFn: () => siteContentApi.section('insights', 'cta'),
  });

  const { data: dbStats = [] } = useQuery({
    queryKey: ['stats', 'insights'],
    queryFn: () => siteContentApi.stats('insights'),
  });

  const stats = dbStats.length > 0
    ? dbStats.slice(0, 4).map(s => ({ icon: s.icon ?? 'ri-star-line', value: s.value, label: s.label }))
    : FALLBACK_STATS;

  const title = statsSection?.title ?? 'Impact by the Numbers';
  const description = statsSection?.description ?? 'Our insights platform connects you with the most successful founders and their proven strategies';

  const ctaTitle = ctaSection?.title ?? 'Want to Share Your Story?';
  const ctaDesc  = ctaSection?.description ?? 'Join our community of successful founders and inspire the next generation of entrepreneurs';
  const cta1 = ctaSection?.cta_text ?? 'Submit Your Story';
  const cta1Url = ctaSection?.cta_url ?? '/promote';
  const cta2 = ctaSection?.cta_text_2 ?? 'Become a Reviewer';
  const cta2Url = ctaSection?.cta_url_2 ?? '/promote';

  return (
    <section className="py-16 bg-gradient-to-br from-[#f7f5ef] to-white">
      <div className="max-w-7xl mx-auto px-6 sm:px-8 lg:px-12">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-[#1F2853] mb-4" style={{ fontFamily: 'Manrope, sans-serif' }}>
            {title}
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto" style={{ fontFamily: 'Poppins, sans-serif' }}>
            {description}
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {stats.map((stat, index) => (
            <div key={index} className="bg-white rounded-xl shadow-lg hover:shadow-xl transition-all duration-300 p-8 text-center group border border-gray-100">
              <div className="w-16 h-16 bg-gradient-to-br from-[#f25a1a] to-[#ff7043] rounded-full flex items-center justify-center mx-auto mb-6 group-hover:scale-110 transition-transform duration-300">
                <div className="w-8 h-8 flex items-center justify-center text-white">
                  <i className={`${stat.icon} text-2xl`}></i>
                </div>
              </div>

              <div className="text-4xl font-bold text-[#1F2853] mb-2" style={{ fontFamily: 'Manrope, sans-serif' }}>
                {stat.value}
              </div>

              <h3 className="text-xl font-semibold text-[#1F2853] mb-3" style={{ fontFamily: 'Manrope, sans-serif' }}>
                {stat.label}
              </h3>

              <p className="text-gray-600 text-sm leading-relaxed" style={{ fontFamily: 'Poppins, sans-serif' }}>
                {FALLBACK_DESCRIPTIONS[stat.label] ?? ''}
              </p>
            </div>
          ))}
        </div>

        {/* Call to Action */}
        <div className="text-center mt-12">
          <div className="bg-gradient-to-r from-[#1F2853] to-[#2a3a6b] rounded-xl p-8 text-white">
            <h3 className="text-2xl font-bold mb-4" style={{ fontFamily: 'Manrope, sans-serif' }}>
              {ctaTitle}
            </h3>
            <p className="text-lg mb-6 opacity-90 max-w-2xl mx-auto" style={{ fontFamily: 'Poppins, sans-serif' }}>
              {ctaDesc}
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to={cta1Url} className="bg-[#f25a1a] hover:bg-[#d14815] text-white px-8 py-3 rounded-lg font-semibold transition-all duration-300 hover:scale-105 whitespace-nowrap text-center" style={{ fontFamily: 'Poppins, sans-serif' }}>
                {cta1}
              </Link>
              <Link to={cta2Url} className="bg-white/10 hover:bg-white/20 text-white border border-white/30 px-8 py-3 rounded-lg font-semibold transition-all duration-300 hover:scale-105 whitespace-nowrap text-center" style={{ fontFamily: 'Poppins, sans-serif' }}>
                {cta2}
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
